name: Run Spring Boot Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spring-boot-test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dannyi9/lansentinel/temurin-nmap:latest
      credentials:
        username: dannyi9
        password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print HOME and Gradle directories
        run: |
          echo "HOME is: $HOME"
          ls -la $HOME
          ls -la $HOME/.gradle

      - name: Enable debug for setup-java
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Cache Gradle packages
        id: gradle-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Show cache result
        run: |
          if [ "${{ steps.gradle-cache.outputs.cache-hit }}" = "true" ]; then
            echo "✅ Gradle cache restored"
          else
            echo "❌ Gradle cache miss"
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        working-directory: backend
        run: chmod +x gradlew

      - name: Run tests
        working-directory: backend
        run: ./gradlew test
