name: Run Spring Boot Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dannyi9/lansentinel/temurin-nmap:latest
      credentials:
        username: dannyi9
        password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Run tests
        working-directory: backend
        run: ./gradlew test
